-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Locations"
(
    id integer NOT NULL,
    name bit varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roads
(
    location1_id integer NOT NULL,
    location2_id integer NOT NULL,
    name character varying[],
    PRIMARY KEY (location1, location2_id)
);
END;